#!/usr/bin/env bash
#custom nginx configuration

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
rp="\n\tlocation /redirect_me {\n\t\treturn 301 https:www.github.com/chaloh-debug;\n\t}\n"
rp1="\n\\terror_page 404 /custom_404.html;\n\tlocation = /var/www/html/custom_404.html {\n\t\tinternal;\n\t}"
rp2="\n\tadd_header X-Served-By \$hostname;"
sudo sed -i "47i\ $rp@rp1@rp2" /etc/nginx/sites-available/default
sudo service nginx reload
