#!/usr/bin/env bash
#run nginx as nginx user
chmod 644 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sed -i "s/#user user nginx/" /etc/nginx/nginx.conf
pkill -9 apache
su nginx -c "service nginx restart"
